apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    deployment: mongodb
  namespace: database-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: mongodb
  template:
    metadata:
      labels:
        name: mongodb-pod
        pod: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        resources:
          requests:
            memory: "50Mi"
          limits:
            memory: "100Mi"
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: database-namespace
spec:
  selector:
    pod: mongodb
  ports:
    - protocol: TCP
      port: 27000
      targetPort: 27017

